package company_package;
import java.util.Scanner;

 @SuppressWarnings("serial")
class MyException extends Exception{
	@Override
	public String toString() {
		return super.toString() + " i am a toString()";
	}
	
	@Override
	public String getMessage() {
		return super.getMessage() + " i am a getMessage()" ;
	}
	
}

public class Java_Practice_Exception_Class {
	public static void main(String[] args) {
		
		@SuppressWarnings("resource")
		Scanner sc = new Scanner(System.in);
		System.out.println("ENTER NUMBER : ");
		int num = sc.nextInt();
		if(num>125) {
			try {
				throw new MyException();
			}
			catch(Exception e) {
				System.out.println("AN ERROR OCCURRED !");
				System.out.print(e.toString()+"\n\n");  	
				System.out.println(e+"\n");				// the e called to String method
				System.out.print(e.getMessage()+"\n\n");
			}
			System.out.println("you can continue with the program ");
		}
	}
}
